matrix:
  include:
#    - os: linux
#      language: java
#      sudo: false # for faster builds
#      jdk: openjdk11
#    - os: osx
#      language: java
#      sudo: false # for faster builds
#      jdk: openjdk11
    - os: windows
      language: c # 'java' not supported, 'generic' causes VM to hang on boot.
      sudo: false # for faster builds
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x .travis/install-linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x .travis/install-osx.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then chmod +x .travis/install-windows.sh; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source .travis/install-linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source .travis/install-osx.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then source .travis/install-windows.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./gradlew test jacocoTestReport; fi
after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash <(curl -s https://codecov.io/bash); fi
