language: java
sudo: false # for faster builds
jdk:
  - openjdk11
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew test jacocoTestReport
  - ./gradlew jar
  - java -jar build/http-server.jar &
  - cd acceptance-tests && bundle install && bundle exec spinach -t @simple-get,@not-found,@simple-head,@simple-options,@not-allowed && cd ..
after_success:
  - bash <(curl -s https://codecov.io/bash)
