language: java
sudo: false # for faster builds
jdk:
  - openjdk11
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew test jacocoTestReport
  - cd acceptance-tests && bundle install && bundle exec spinach && cd ..
after_success:
  - bash <(curl -s https://codecov.io/bash)
