matrix:
  include:
  - os: linux
    language: java
    sudo: false
    jdk: openjdk11
  - os: osx
    language: java
    sudo: false
    jdk: openjdk11
#    Disable Windows due to ENV var's bug with Travis - ENV var's required for AWS deployment.
#    See https://travis-ci.community/t/choco-install-hangs-forever/307/6
#  - os: windows
#    language: c
#    sudo: false
before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install -y openjdk --version 11.0
      export JAVA_HOME="/c/Program Files/OpenJDK/jdk-11"
      export PATH="$JAVA_HOME/bin:$PATH"
      gem install bundle
      export GRADLE_OPTS=-Dorg.gradle.daemon=false # Gradle daemon causes Windows VM to hang; disable it.
    fi
  - chmod +x gradlew
script:
  - |
    if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
      ./gradlew check
      ./gradlew test jacocoTestReport
    fi
  - ./gradlew jar
  - java -jar build/http-server.jar &
  - cd acceptance-tests
  - bundle install
  - bundle exec spinach
  - kill %1
  - cd ..
after_success: if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash <(curl -s https://codecov.io/bash); fi
deploy:
  provider: script
  skip_cleanup: false
  script: chmod +x deploy.sh && ./deploy.sh
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux
